---
version: 0.2

phases:
  build:
    commands:
      - |
        docker run --rm -i \
          -v $PWD:/docs \
          -e MERCHANT_ID=$MERCHANT_ID \
          sphinxdoc/sphinx \
          sphinx-build -b html docs build
  post_build:
    commands:
      - |
        aws s3 sync ./build s3://ui.postpay.io \
          --cache-control max-age=14400,public \
          --acl public-read
      - |
        aws cloudfront create-invalidation \
          --distribution-id $DISTRIBUTION_ID \
          --paths "/*"
